import { useRef, useState } from 'react'
import type { KeyboardEvent, MouseEvent } from 'react'
import { companies, contact, trackEvent } from './siteData'
import './CompanyContent.css'

type Navigate = (event: MouseEvent<HTMLAnchorElement>) => void
function Arrow() { return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 19 19 5M5 5h14v14" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" /></svg> }
function Icon({ type }: { type: 'phone' | 'pin' | 'message' | 'arrow' }) {
  return <svg width="24" height="24" viewBox="0 0 24 24" fill="none" aria-hidden="true" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">{type === 'phone' ? <path d="m8 3 3 5-3 2c1 3 3 5 6 6l2-3 5 3-1 4c-1 2-6 1-11-4S3 6 4 4l4-1Z" /> : type === 'pin' ? <><path d="M19 10c0 5-7 11-7 11S5 15 5 10a7 7 0 1 1 14 0Z" /><circle cx="12" cy="10" r="2.5" /></> : type === 'message' ? <path d="M20 4H4v13h4v4l5-4h7V4ZM8 8h8M8 12h5" /> : <path d="M4 12h16m-6-6 6 6-6 6" />}</svg>
}

const solutions = [
  { label: 'Ordenar mi contabilidad', category: 'Contabilidad y asesoría', brand: companies[0], title: 'Más claridad para las decisiones de tu empresa.', copy: 'Si buscas orientación para organizar la información de tu negocio, empieza por la asesoría contable. A&M Asesores Contables reúne las especialidades contable, tributaria, laboral y empresarial.', items: ['Asesoría contable y revisión de tus necesidades', 'Orientación tributaria y laboral', 'Acompañamiento en decisiones empresariales'], note: 'Cuéntanos a qué se dedica tu empresa y qué aspecto de su gestión necesitas revisar.', cta: 'Conocer la asesoría', url: 'https://www.asesorescontablesaym.com/', image: '/images/accounting.jpg' },
  { label: 'Facturar electrónicamente', category: 'ContaWeb · Facturación Electrónica', brand: companies[1], title: 'El siguiente paso para gestionar tus comprobantes.', copy: 'Conoce la solución de Facturación Electrónica de ContaWeb A&M y consulta sus opciones según la actividad y las necesidades de tu negocio.', items: ['Información sobre facturación electrónica', 'Consulta de planes y funcionalidades', 'Acceso al sitio especializado de Facturación'], note: 'Para orientar tu consulta, indica tu actividad y cómo emites tus comprobantes actualmente.', cta: 'Explorar Facturación', url: 'https://contawebaym.net/', image: '/images/billing.jpg' },
  { label: 'Integrar la gestión con ERP', category: 'ContaWeb · Sistema ERP', brand: companies[1], title: 'Conecta la información que mueve tu negocio.', copy: 'Explora ContaWebAyM ERP y sus módulos de gestión. Un acceso específico para conocer cómo la plataforma aborda la contabilidad, la facturación y los inventarios.', items: ['Gestión contable e información empresarial', 'Facturación e inventarios', 'Consulta de módulos para tu operación'], note: 'Comparte qué procesos quieres integrar y qué herramientas utilizas hoy.', cta: 'Explorar el ERP', url: 'https://contawebaym.com/', image: '/images/technology.jpg' },
  { label: 'Alquilar vehículos o maquinaria', category: 'Renting Car · Movilidad', brand: companies[2], title: 'Movilidad para tu próximo proyecto.', copy: 'Consulta por el alquiler de vehículos y maquinaria para empresas y personas. Comunícate con el grupo para explicar tu necesidad y conocer las opciones disponibles.', items: ['Alquiler para empresas y personas', 'Consulta de vehículos y maquinaria', 'Coordinación según fechas y tipo de uso'], note: 'Indica qué necesitas, dónde lo utilizarás y durante cuánto tiempo.', cta: 'Consultar por WhatsApp', url: `https://wa.me/${contact.whatsapp}?text=${encodeURIComponent('Hola, quisiera consultar sobre alquiler de vehículos o maquinaria con Renting Car A&M.')}`, image: '/images/car.jpg' },
]

export function SolutionsExplorer() {
  const [active, setActive] = useState(0)
  const tabs = useRef<(HTMLButtonElement | null)[]>([])
  const solution = solutions[active]
  function keyboard(event: KeyboardEvent, index: number) {
    const next = event.key === 'ArrowDown' ? (index + 1) % solutions.length : event.key === 'ArrowUp' ? (index - 1 + solutions.length) % solutions.length : event.key === 'Home' ? 0 : event.key === 'End' ? solutions.length - 1 : null
    if (next === null) return
    event.preventDefault(); setActive(next); tabs.current[next]?.focus()
  }
  return <section className="solutions-section content-section" id="soluciones" tabIndex={-1} aria-labelledby="solutions-title">
    <div className="editorial-heading"><div><p className="eyebrow"><span className="tiny-square" /> Soluciones para cada necesidad</p><h2 id="solutions-title">¿Qué quieres impulsar<br /><span>en tu negocio?</span></h2></div><p>Elige por dónde empezar. Te acercamos a la especialidad y al canal adecuados para tu consulta.</p></div>
    <div className="solutions-layout"><div className="solution-tabs" role="tablist" aria-label="Necesidades de tu negocio" aria-orientation="vertical">{solutions.map((s, i) => <button key={s.label} ref={node => { tabs.current[i] = node }} id={`solution-tab-${i}`} role="tab" aria-selected={i === active} aria-controls={`solution-panel-${i}`} tabIndex={i === active ? 0 : -1} onClick={() => setActive(i)} onKeyDown={e => keyboard(e, i)}><span className="solution-number">0{i + 1}</span><span>{s.label}</span><Icon type="arrow" /></button>)}</div>
      {solutions.map((s, i) => <div key={s.label} role="tabpanel" id={`solution-panel-${i}`} aria-labelledby={`solution-tab-${i}`} hidden={active !== i} tabIndex={0}>{active === i && <article className="solution-detail"><div className="solution-visual"><img src={s.image} alt="" loading="lazy" width="800" height="600" /><span className="solution-logo"><img src={s.brand.logo} alt={s.brand.name} width="190" height="70" /></span><span className="solution-visual-label">{s.brand.category}</span></div><div className="solution-copy"><p className="eyebrow">{s.category}</p><h3>{s.title}</h3><p>{s.copy}</p><ul>{s.items.map(item => <li key={item}><span aria-hidden="true">↗</span>{item}</li>)}</ul><p className="solution-note">{s.note}</p><a href={s.url} className="orange-button" target="_blank" rel="noopener noreferrer" onClick={() => trackEvent(s.brand.id === 'renting' ? 'whatsapp_click' : 'brand_outbound', { brand: s.brand.id, product: s.category, placement: 'solutions' })}>{s.cta}<Arrow /><span className="sr-only"> (abre en otra pestaña)</span></a></div></article>}</div>)}
    </div><p className="solution-footnote">{solution.brand.name} · Una especialidad de Grupo AyM</p>
  </section>
}

export function GettingStarted({ navigate }: { navigate: Navigate }) {
  const steps = [
    ['Cuéntanos tu necesidad', 'Describe qué quieres resolver: contabilidad, facturación, gestión empresarial o movilidad.'],
    ['Elige el canal adecuado', 'Visita el sitio de cada solución o contacta con nuestra central si necesitas orientación.'],
    ['Coordina el siguiente paso', 'Consulta el alcance, las opciones y las condiciones del servicio antes de empezar.'],
  ]
  return <section className="getting-started content-section" aria-labelledby="start-title"><div className="editorial-heading"><div><p className="eyebrow">De la idea a la conversación</p><h2 id="start-title">Empezar puede<br /><span>ser sencillo.</span></h2></div><a className="text-link" href="/contacto" onClick={navigate}>Hablemos de tu proyecto <Arrow /></a></div><ol className="steps-grid">{steps.map(([title, copy], i) => <li key={title}><div className="step-top"><span>0{i + 1}</span><Icon type={i === 0 ? 'message' : i === 1 ? 'phone' : 'arrow'} /></div><h3>{title}</h3><p>{copy}</p></li>)}</ol></section>
}

const questions = [
  ['¿Qué servicios reúne Grupo AyM?', 'El grupo reúne tres especialidades: asesoría contable, tributaria, laboral y empresarial con A&M Asesores Contables; soluciones de software con ContaWeb A&M; y alquiler de vehículos y maquinaria con Renting Car A&M.'],
  ['¿Facturación Electrónica y ERP son lo mismo?', 'Son dos soluciones que presentamos bajo la marca ContaWeb A&M. Facturación Electrónica tiene su sitio en contawebaym.net y el ERP en contawebaym.com. En la sección Soluciones puedes explorar ambos accesos y consultar cuál se ajusta a tu operación.'],
  ['¿Cómo puedo consultar por un servicio?', `Puedes llamar a la central ${contact.landline}, escribir al WhatsApp ${contact.phone} o usar los canales de la página Contacto. Si buscas asesoría contable, también tienes el correo informes@asesorescontablesaym.com.`],
  ['¿Renting Car atiende también a personas?', 'Sí. La propuesta de Renting Car A&M contempla alquiler de vehículos y maquinaria para empresas y personas. Para consultar disponibilidad, indica el tipo de vehículo o maquinaria, las fechas y el uso que necesitas.'],
  ['¿Dónde están ubicados?', `Nos encuentras en ${contact.address}. En Contacto tienes el mapa y el acceso a Google Maps. Llámanos o escríbenos para coordinar tu visita.`],
  ['¿Qué información conviene tener al consultar?', 'Tu nombre, un canal de contacto y una breve descripción de lo que necesitas. Para software, explica qué procesos deseas gestionar; para asesoría, el tema que quieres revisar; y para alquiler, las fechas y el tipo de uso.'],
]
export function FrequentlyAsked({ navigate }: { navigate: Navigate }) {
  return <section className="faq-section content-section" id="preguntas" tabIndex={-1} aria-labelledby="faq-title"><div className="faq-intro"><p className="eyebrow"><span className="tiny-square" /> Antes de empezar</p><h2 id="faq-title">Tus preguntas.<br /><span>Respuestas claras.</span></h2><p>Conoce el grupo y encuentra la mejor forma de ponerte en contacto.</p><a className="text-link" href="/contacto" onClick={navigate}>Tengo otra consulta <Arrow /></a></div><div className="faq-list">{questions.map(([question, answer], i) => <details key={question}><summary><span className="faq-number">0{i + 1}</span><h3>{question}</h3><span className="faq-plus" aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>
}

export function LocationSection({ showDirectory = false }: { showDirectory?: boolean }) {
  return <section className={`location-section content-section ${showDirectory ? 'with-directory' : ''}`} id="ubicacion" tabIndex={-1} aria-labelledby="location-title"><div className="location-info"><p className="eyebrow"><Icon type="pin" /> Santiago de Surco · Lima</p><h2 id="location-title">También podemos<br /><span>conversar en persona.</span></h2><p className="location-address">{contact.address}</p><p>Comunícate con nosotros para coordinar tu visita o resolver una consulta sobre nuestras marcas.</p><div className="location-phone"><span className="contact-icon"><Icon type="phone" /></span><div><span>Central telefónica</span><a href={`tel:${contact.landlineHref}`} onClick={() => trackEvent('phone_click', { placement: 'location' })}>{contact.landline}</a></div></div><div className="location-actions"><a className="orange-button" href={contact.mapsUrl} onClick={() => trackEvent('map_click', { placement: 'location' })} target="_blank" rel="noopener noreferrer">Abrir en Google Maps<Arrow /></a><a className="text-link" href={`https://wa.me/${contact.whatsapp}?text=${encodeURIComponent('Hola, quisiera coordinar una visita a Grupo AyM.')}`} target="_blank" rel="noopener noreferrer" onClick={() => trackEvent('whatsapp_click', { placement: 'location' })}>Coordinar por WhatsApp <Arrow /></a></div></div>
    {showDirectory && <div className="location-directory"><p className="eyebrow">Estamos a una conversación</p><a href={`tel:${contact.landlineHref}`} onClick={() => trackEvent('phone_click', { placement: 'directory' })}><span>Llame a nuestra central<strong>{contact.landline}</strong></span><Icon type="phone" /></a><a href={`mailto:${contact.email}`} onClick={() => trackEvent('email_click', { placement: 'directory' })}><span>Escríbenos<strong>{contact.email}</strong></span><Arrow /></a><a href={`https://wa.me/${contact.whatsapp}`} target="_blank" rel="noopener noreferrer" onClick={() => trackEvent('whatsapp_click', { placement: 'directory' })}><span>Conversemos por WhatsApp<strong>{contact.phone}</strong></span><Icon type="message" /></a></div>}<div className="location-map"><iframe src={contact.mapEmbed} width="600" height="450" title="Ubicación de Grupo AyM en Av. Santiago de Surco 3573" allowFullScreen loading="lazy" referrerPolicy="strict-origin-when-cross-origin" /><a href={contact.mapsUrl} target="_blank" rel="noopener noreferrer" className="map-caption">Av. Santiago de Surco 3573 <Arrow /></a></div>
  </section>
}

export function GroupApproach({ navigate }: { navigate: Navigate }) {
  return <section className="group-approach content-section"><div className="editorial-heading"><div><p className="eyebrow">Distintas necesidades, una visión compartida</p><h2>El valor de tener<br /><span>más de una perspectiva.</span></h2></div><p>Una empresa necesita información, herramientas y recursos para operar. Nuestras marcas permiten explorar esas necesidades desde especialidades que se complementan.</p></div><div className="approach-grid">{[
    ['Comprender', 'La información como punto de partida.', 'La asesoría contable ayuda a poner en contexto las preguntas sobre la gestión de tu empresa.'],
    ['Conectar', 'La tecnología al servicio de la gestión.', 'Las soluciones de ContaWeb ofrecen caminos para conocer y organizar distintos procesos del negocio.'],
    ['Avanzar', 'La movilidad como parte de la operación.', 'Los servicios de alquiler amplían las opciones para proyectos y necesidades de empresas y personas.'],
  ].map(([word, title, text], i) => <article key={word}><span className="approach-index">0{i + 1} /</span><p className="approach-word">{word}</p><h3>{title}</h3><p>{text}</p></article>)}</div><a href="/#soluciones" onClick={navigate} className="text-link">Encuentra la solución para tu negocio <Arrow /></a></section>
}
